//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Orders()
        {
            this.Tbl_OrderProducts = new HashSet<Tbl_OrderProducts>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<int> ShippingDetailsId { get; set; }
    
        public virtual Tbl_ShippingDetails Tbl_ShippingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderProducts> Tbl_OrderProducts { get; set; }
    }
}
